apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: test
type: Opaque
data:
  rabbitmq-user: YWRtaW4=          # base64 encoded "admin"
  rabbitmq-password: cGFzc3dvcmQ=  # base64 encoded "password"