apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ebs-fast
  namespace: staging
provisioner: ebs.csi.aws.com  # Use the CSI driver
parameters:
  type: gp2  # General Purpose SSD
reclaimPolicy: Retain  # Retain the EBS volume even if the PVC is deleted
volumeBindingMode: Immediate