apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: test
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=          # base64 encoded "postgres"
  postgres-password: cGFzc3dvcmQ=      # base64 encoded "password"